### ISSUE TITLE
[Feature Request] Add a setting to activate manual rolls

### ISSUE THREAD

**Issue by Rowiz49** [theripper93/real-dice#1]
Add a setting to have it on manual rolls by default so that players on touch screens can use it.

**Comment by theripper93** [comment]
Sorry, forgot to add the disclaimer in the module readme

Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
