### ISSUE TITLE
Enable Player Controlled Token Always be Manual Roll Setting

### ISSUE THREAD

**Issue by Kowabunga86** [theripper93/real-dice#2]
Hey there!
Want to say not a issue but more of a request.
I play games in person and online. In person I use automated tools to track things like concentration checks to help me not forget those things.
Something I think would be amazing is if I could assign if specific player owned tokens are rolled by the player or DM it forces a manual roll. This would help when playing with real life dice but other players and/or the DM could use automation tools if they liked. This would be helpful so I do not keep accidently to swap manual roll on/off between each players turn.

Example:
DM - Real Dice Roll if a player controlled token, if not player controlled token ignore Real Dice.
Player 1 - Player tells DM roll of dice. DM inputs roll into Real Dice for player.
Player 2 - Ignore Real Dice as player wants to use automation.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
