### ISSUE TITLE
Module hooks all dice rolls

### ISSUE THREAD

**Issue by FlorianH1989** [theripper93/real-dice#3]
One of my players is currently playing a hexblade warlock. She is using the hex spell and the hexblade curse in combination and gets to add her proficiency modifier for damage rolls and 1d6 necrotic damage. 

My player gets multiple prompts for different stages of the damage roll. In this case it looks like this:

1d8 + 4
1d8 + 4 + 2
1d8 + 4 + 2 + 1d6
She enters her dice rolls and only the last prompt is calculated. So the math works and she gets all of her bonuses. The damage of the first two prompts are neglected.

Is there a way to display only the correct prompt?

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
