### ISSUE TITLE
When applying bonus damages the module prompts players to enter dice rolls multiple times

### ISSUE THREAD

**Issue by FlorianH1989** [theripper93/real-dice#4]
**I have disabled all other modules: **False, I had to enable Chris Premades and Midi-QoL
**Module(s) **Real Dice 1.1.3
**Conflicting Module(s) **
**Foundry and System version **Foundry 11.315, DnD5e 2.4.1
**OS, Hosting, Browser (if applicable) **Linux Debian Servier via Docker Compose, Google Chrome (120.0.6099.216)
**Short description of bug **When applying bonus damages the module prompts players to enter dice rolls multiple times.
**Simple steps to reproduce the bug **

1. Add bonus damage effect to PC. 
For example: Chris Premades's "Eldritch Invocations: Agonizing Blast"
2. Make an attack roll with Eldritch Blast against a target
3. Enter a dice value which will hit the target
4. First prompt for damage is 1d10 (Force)
5. Second prompt for damage is 1d10 (Force) + CHA Modifier

Only the second prompt gets calculated. So the math and bonus is fine.
Is there a way to not show the first damage prompt?

**Screenshots and/or Console Errors**
<img width="787" alt="Bildschirm­foto 2024-01-27 um 17 44 18" src="https://github.com/theripper93/real-dice/assets/110769699/a6a99beb-20f1-40b9-b271-9b86a6b3844f">
<img width="641" alt="Bildschirm­foto 2024-01-27 um 17 45 00" src="https://github.com/theripper93/real-dice/assets/110769699/3b1bdb59-e65d-43bc-95e0-21710679bebd">
<img width="374" alt="Bildschirm­foto 2024-01-27 um 17 46 04" src="https://github.com/theripper93/real-dice/assets/110769699/db73237f-0b27-4f78-b6ba-2b73927ed45e">
<img width="423" alt="Bildschirm­foto 2024-01-27 um 17 46 10" src="https://github.com/theripper93/real-dice/assets/110769699/f5561ab9-01e2-453c-82d2-e349b8f9fde4">
<img width="296" alt="Bildschirm­foto 2024-01-27 um 17 46 22" src="https://github.com/theripper93/real-dice/assets/110769699/79719976-3649-43ee-a7b0-bc08cc82d6e2">

**Comment by theripper93** [comment]
Real dice is simply a middle layer that intercepts rolls. If modules are doing rolls behind the scenes they will be intercepted as well. Please verify that this issue happens with no modules, otherwise you'll have to ask the module developers to change the way they process automations.

I can confirm that adding an effect that adds for example a d10 to weapon damage does not cause any double prompt

**Comment by FlorianH1989** [comment]
Issue can be closed. The double prompt cannot be reproduced without any modules enabled. I'll ask Chris, if he sees any way to change the automation

**Comment by chrisk123999** [comment]
My module does a new roll under the hood to add bonus damage. For example: https://github.com/chrisk123999/chris-premades/blob/master/scripts/macros/spells/hex.js#L138
I don't think there is an easy fix.
